config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'tasks#index', as: :authenticated_root
  end

  resources :tasks do
    member do
      post :toggle
    end
    resources :subtasks do
      member do
        post :toggle
      end
    end
    member do
      patch :complete
    end
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task

  validates :task, presence: true
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :subtasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  protected

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_public_tasks
    @public_tasks = Task.where(public: true)
  end

  def task_owner?
    unless @task.owner == current_user
      redirect_to root_path, alert: "You don't have access to that task."
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation, :current_password)
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_task
  before_action :task_owner?
  before_action :set_subtask, only: [:show, :edit, :update, :destroy, :toggle]

  # GET /subtasks
  # GET /subtasks.json
  def index
    @subtasks = Subtask.all
  end

  # GET /subtasks/1
  # GET /subtasks/1.json
  def show
  end

  # GET /subtasks/new
  def new
    @subtask = @task.subtasks.new
  end

  # GET /subtasks/1/edit
  def edit
  end

  # POST /subtasks
  # POST /subtasks.json
  def create
    @subtask = @task.subtasks.new(subtask_params)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to @task, notice: 'Subtask was successfully created.' }
        format.json { render :show, status: :created, location: [@subtask.task, @subtask] }
      else
        format.html { render :new }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtasks/1
  # PATCH/PUT /subtasks/1.json
  def update
    respond_to do |format|
      if @subtask.update(subtask_params)
        format.html { redirect_to @task, notice: 'Subtask was successfully updated.' }
        format.json { render :show, status: :ok, location: @subtask }
      else
        format.html { render :edit }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1
  # DELETE /subtasks/1.json
  def destroy
    @subtask.destroy
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Subtask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle
    @subtask.update_attributes(completed: !@subtask.completed)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtask_params
      params.require(:subtask).permit(:name, :completed, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete, :toggle]
  before_action :set_public_tasks, only: [:index]
  before_action :task_owner?, except: [:index, :new, :create]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle
      @task.update_attributes(completed: !@task.completed)
  end

  def complete
    if @task.update_attributes(completed: true)
      redirect_to @task,
                  notice: "Congratulations, this task is complete!"
    else
      redirect_to @task, alert: "Unable to complete task."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :completed, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>Welcome to Todo's</h1>

<p>
  <%= link_to "Sign in", new_user_session_path %> or
  <%= link_to "Sign up", new_user_registration_path %> to continue.
</p>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name == 'notice' ? 'success' : 'warning' %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Task Manager", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Tasks", tasks_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= hidden_field_tag :authenticity_token, form_authenticity_token %><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= form_with(model: [subtask.task, subtask]) do |f| %>
  <% if subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
      <% subtask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :subtask_name %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, id: :subtask_completed %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", subtask.task, class: "btn btn-default", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/subtasks/_subtask.html.erb
<tr class="task">
  <td>
    <label id="<%= dom_id(subtask) %>" class="<%= subtask.completed? ? 'completed' : nil %>">
      <%= check_box_tag 'completed', subtask.id, subtask.completed,
          data: {
            remote: true,
            url: toggle_task_subtask_path(subtask.task, subtask),
            method: :post
          },
          style: "font-size: 300%"
      %>
      <%= subtask.name %>
    </label>
  </td>
  <td class="task-actions">
    <%= link_to edit_task_subtask_path(subtask.task, subtask),
        class: "btn btn-xs btn-default" do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      Edit
    <% end %>
    <%= link_to [subtask.task, subtask], method: :delete,
        data: { confirm: 'Are you sure?' },
        class: "btn btn-default btn-xs" do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
      Delete
    <% end %>
  </td>
</tr>

app/views/subtasks/edit.html.erb
<h1>Editing Subtask</h1>

<%= render 'form', subtask: @subtask %>

app/views/subtasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subtasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subtasks.each do |subtask| %>
      <tr>
        <td><%= subtask.name %></td>
        <td><%= subtask.completed %></td>
        <td><%= subtask.task_id %></td>
        <td><%= link_to 'Show', subtask %></td>
        <td><%= link_to 'Edit', edit_task_subtask_path(subtask) %></td>
        <td><%= link_to 'Destroy', subtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subtask', new_task_subtask_path %>

app/views/subtasks/new.html.erb
<h1>New Subtask</h1>

<%= render 'form', subtask: @subtask %>

app/views/subtasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subtask.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @subtask.task %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @subtask.completed %>
</p>


<%= link_to 'Edit', edit_task_subtask_path(@subtask) %> |
<%= link_to 'Back', task_subtasks_path %>

app/views/subtasks/toggle.js.erb
$('#<%= dom_id(@subtask) %>').toggleClass('completed');

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :task_name %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, id: :task_completed %>
  </div>

  <div class="form-group">
    <%= f.label :public %>
    <%= f.check_box :public, id: :task_public %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <% cancel_path = (task.persisted? ? task_path(task) : tasks_path) %>
    <%= link_to "Cancel", cancel_path, class: "btn btn-default", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr class="task">
  <td>
    <label id="<%= dom_id(task) %>" class="<%= task.completed? ? 'completed' : nil %>">
      <%= check_box_tag 'completed', task.id, task.completed,
          data: {
            remote: true,
            url: toggle_task_path(task),
            method: :post
          },
          style: "font-size: 300%"
      %>
      <%= task.name %>
    </label>
  </td>
  <td class="task-actions">
    <%= link_to task_path(task),
                class: "btn btn-xs btn-default" do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      Show
    <% end %>
    <%= link_to edit_task_path(task),
        class: "btn btn-xs btn-default" do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      Edit
    <% end %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h2 class="heading">
  Tasks
  <%= link_to new_task_path, class: "btn btn-default btn-sm btn-inline" do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add Task
  <% end %>
</h2>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th class="task-actions">Actions</th>
  </tr>
  </thead>

  <tbody>
  <%= render @tasks %>
  </tbody>
</table>

<h2 class="heading">
  Public Tasks
</h2>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th class="task-actions">Actions</th>
  </tr>
  </thead>

  <tbody>
  <%= render @public_tasks %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2 class="heading">
  Task
</h2>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th class="task-actions">Actions</th>
  </tr>
  </thead>

  <tbody>
  <%= render @task %>
  </tbody>
</table>

<p>
  Owner:
  <%= @task.owner.email %>
</p>

<hr class="divider">

<h2 class="heading">
  Subtasks
  <%= link_to new_task_subtask_path(@task), class: "btn btn-default btn-sm btn-inline" do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add Subtask
  <% end %>
</h2>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th class="task-actions">Actions</th>
  </tr>
  </thead>

  <tbody>
  <%= render @task.subtasks %>
  </tbody>
</table>

app/views/tasks/toggle.js.erb
$('#<%= dom_id(@task) %>').toggleClass('completed');